apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: robot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        prometheus: scrape
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: catalogue
          image: ghcr.io/mick-proj/devops-programme/catalogue:42b00d8b2beb0974b959649c20d28737b0469e7c
          ports:
            - containerPort: 8080

