apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: robot-shop
  labels:
    app: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

