apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robot-shop
  labels:
    app: cart
    prometheus: scrape
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

