apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mick-proj/devops-programme.git
    targetRevision: main
    path: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: robot-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

