apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/secrets.yaml
  - web/deployment.yaml
  - web/service.yaml
  - cart/deployment.yaml
  - cart/service.yaml
  - catalogue/deployment.yaml
  - catalogue/service.yaml
